from __future__ import annotations

from datetime import datetime

from rmbench.workload.engine import TABLE_NAMES


def insert_statement(csv_file_path: str, *, access_key: str, secret_key: str) -> str:
    builder = {
        "fact_daily_od_bucket": _od_insert_query,
        "fact_daily_leg_physical_inventory": _leg_insert_query,
        "fact_passenger_event": _passenger_insert_query,
    }[_table_for_path(csv_file_path)]
    return builder(csv_file_path, access_key=access_key, secret_key=secret_key) + " SETTINGS insert_deduplicate = 0"


def _table_for_path(csv_file_path: str) -> str:
    table_name = next((name for name in TABLE_NAMES if name in csv_file_path), None)
    if table_name is None:
        raise ValueError(f"Could not determine table for {csv_file_path}.")
    return table_name


def delete_query(
    *, table_name: str, sale_window: tuple[datetime, datetime], batch_start_timestamp: datetime
) -> str:
    # ClickHouse rejects an ISO8601 string carrying a UTC offset
    start, end = (value.strftime("%Y-%m-%dT%H:%M:%S") for value in sale_window)
    batch_time = batch_start_timestamp.strftime("%Y-%m-%dT%H:%M:%S")
    return f"""
        DELETE FROM {table_name}
        WHERE event_datetime >= toDateTime('{start}', 'UTC')
            AND event_datetime < toDateTime('{end}', 'UTC')
            AND insertion_datetime < toDateTime('{batch_time}', 'UTC')
        SETTINGS
            lightweight_deletes_sync = 0
    """


def _od_insert_query(csv_file_path: str, *, access_key: str, secret_key: str) -> str:
    return f"""
    INSERT INTO fact_daily_od_bucket (
        time,
        day_x,
        event_datetime,
        transporter_type,
        entity_name,
        route_name,
        service_id,
        service_departure_date,
        service_number,
        service_labels,
        service_status,
        service_origin_station_name,
        service_destination_station_name,
        service_departure_datetime,
        service_arrival_datetime,
        service_timezone,
        service_budget_objective,
        service_yield_objective,
        service_capacity,
        service_lid,
        service_max_leg_load_factor,
        service_max_leg_cumulative_sum_net_bookings,
        service_optimization_status,
        service_pointer,
        market_name,
        market_rank,
        market_list_alerts,
        market_cabin_max_leg_load_factor,
        market_cabin_max_leg_cumulative_sum_net_bookings,
        od_id,
        od_status,
        od_origin_station_name,
        od_destination_station_name,
        od_departure_datetime,
        od_arrival_datetime,
        od_rank,
        reference_service_number,
        reference_service_departure_date,
        cabin_name,
        od_cabin_forecasted_traffic,
        od_cabin_forecasted_revenue_vat_inc,
        od_cabin_forecasted_revenue_vat_exc,
        od_cabin_optimized_traffic,
        od_cabin_optimized_revenue_vat_inc,
        od_cabin_optimized_revenue_vat_exc,
        od_cabin_last_predicted,
        od_cabin_last_observed,
        od_cabin_pointer,
        family_name,
        bucket_name,
        bucket_order,
        has_pricing_changed_day_x,
        has_pricing_changed_bucket,
        cumulative_sum_net_revenue_vat_inc,
        cumulative_sum_net_revenue_vat_exc,
        cumulative_sum_net_ancillary_revenue_vat_inc,
        cumulative_sum_net_ancillary_revenue_vat_exc,
        sum_net_revenue_vat_inc,
        sum_net_revenue_vat_exc,
        sum_net_ancillary_revenue_vat_inc,
        sum_net_ancillary_revenue_vat_exc,
        availability_start_day,
        availability_end_day,
        cumul_availability_start_day,
        cumul_availability_end_day,
        cumulative_sum_net_bookings,
        sum_confirmed_bookings,
        sum_net_bookings,
        is_first_available_start_day,
        is_first_available_end_day,
        price_vat_inc,
        cabin_capacity,
        cabin_lid,
        bucket_authorization_start_day,
        bucket_authorization_end_day,
        forecast_full_day_x,
        optimization_full_day_x,
        unconstrained_demand_bookings,
        unconstrained_demand_revenue,
        unconstrained_forecast_bookings,
        unconstrained_forecast_revenue,
        is_optim_current,
        is_last,
        insertion_datetime
    )
    SELECT
        event_datetime as time,
        toInt32(day_x) as day_x,
        parseDateTime64BestEffort(event_datetime, 3, 'UTC') as event_datetime,
        transporter_type,
        entity_name,
        route_name,
        toInt64(service_id) as service_id,
        toDate(service_departure_date) as service_departure_date,
        service_number,
        multiIf(
            ifNull(service_labels, '') = '', [],
            splitByString('#~#', ifNull(service_labels, ''))
        ) as service_labels,
        service_status,
        service_origin_station_name,
        service_destination_station_name,
        parseDateTime64BestEffort(service_departure_datetime, 3, 'UTC') as service_departure_datetime,
        parseDateTime64BestEffort(service_arrival_datetime, 3, 'UTC') as service_arrival_datetime,
        service_timezone,
        toDecimal64OrNull(service_budget_objective, 2) as service_budget_objective,
        toDecimal64OrNull(service_yield_objective, 2) as service_yield_objective,
        toNullable(toInt32(service_capacity)) as service_capacity,
        toNullable(toInt32(service_lid)) as service_lid,
        toDecimal64OrNull(service_max_leg_load_factor, 2) as service_max_leg_load_factor,
        toNullable(toInt32(service_max_leg_cumulative_sum_net_bookings)) as service_max_leg_cumulative_sum_net_bookings,
        service_optimization_status,
        toBool(service_pointer) as service_pointer,
        market_name,
        toInt32(market_rank) as market_rank,
        multiIf(
            ifNull(market_list_alerts, '') = '', [],
            splitByString('#~#', ifNull(market_list_alerts, ''))
        ) as market_list_alerts,
        toDecimal64OrNull(market_cabin_max_leg_load_factor, 2) as market_cabin_max_leg_load_factor,
        toNullable(toInt32(market_cabin_max_leg_cumulative_sum_net_bookings))
            as market_cabin_max_leg_cumulative_sum_net_bookings,
        toInt64(od_id) as od_id,
        od_status,
        od_origin_station_name,
        od_destination_station_name,
        parseDateTime64BestEffort(od_departure_datetime, 3, 'UTC') as od_departure_datetime,
        parseDateTime64BestEffort(od_arrival_datetime, 3, 'UTC') as od_arrival_datetime,
        toInt32(od_rank) as od_rank,
        reference_service_number,
        toNullable(toDate(reference_service_departure_date)) as reference_service_departure_date,
        cabin_name,
        toDecimal64OrNull(od_cabin_forecasted_traffic, 2) as od_cabin_forecasted_traffic,
        toDecimal64OrNull(od_cabin_forecasted_revenue_vat_inc, 2) as od_cabin_forecasted_revenue_vat_inc,
        toDecimal64OrNull(od_cabin_forecasted_revenue_vat_exc, 2) as od_cabin_forecasted_revenue_vat_exc,
        toDecimal64OrNull(od_cabin_optimized_traffic, 2) as od_cabin_optimized_traffic,
        toDecimal64OrNull(od_cabin_optimized_revenue_vat_inc, 2) as od_cabin_optimized_revenue_vat_inc,
        toDecimal64OrNull(od_cabin_optimized_revenue_vat_exc, 2) as od_cabin_optimized_revenue_vat_exc,
        toDecimal64OrNull(od_cabin_last_predicted, 2) as od_cabin_last_predicted,
        toDecimal64OrNull(od_cabin_last_observed, 2) as od_cabin_last_observed,
        toBool(od_cabin_pointer) as od_cabin_pointer,
        family_name,
        bucket_name,
        toInt32(bucket_order) as bucket_order,
        toBool(has_pricing_changed_day_x) as has_pricing_changed_day_x,
        toBool(has_pricing_changed_bucket) as has_pricing_changed_bucket,
        toDecimal64OrNull(cumulative_sum_net_revenue_vat_inc, 2) as cumulative_sum_net_revenue_vat_inc,
        toDecimal64(cumulative_sum_net_revenue_vat_exc, 2) as cumulative_sum_net_revenue_vat_exc,
        toDecimal64(cumulative_sum_net_ancillary_revenue_vat_inc, 2) as cumulative_sum_net_ancillary_revenue_vat_inc,
        toDecimal64(cumulative_sum_net_ancillary_revenue_vat_exc, 2) as cumulative_sum_net_ancillary_revenue_vat_exc,
        toDecimal64(sum_net_revenue_vat_inc, 2) as sum_net_revenue_vat_inc,
        toDecimal64(sum_net_revenue_vat_exc, 2) as sum_net_revenue_vat_exc,
        toDecimal64(sum_net_ancillary_revenue_vat_inc, 2) as sum_net_ancillary_revenue_vat_inc,
        toDecimal64(sum_net_ancillary_revenue_vat_exc, 2) as sum_net_ancillary_revenue_vat_exc,
        toNullable(toInt32(availability_start_day)) as availability_start_day,
        toNullable(toInt32(availability_end_day)) as availability_end_day,
        toInt32(cumul_availability_start_day) as cumul_availability_start_day,
        toInt32(cumul_availability_end_day) as cumul_availability_end_day,
        toNullable(toInt32(cumulative_sum_net_bookings)) as cumulative_sum_net_bookings,
        toNullable(toInt32(sum_confirmed_bookings)) as sum_confirmed_bookings,
        toNullable(toInt32(sum_net_bookings)) as sum_net_bookings,
        toBool(is_first_available_start_day) as is_first_available_start_day,
        toBool(is_first_available_end_day) as is_first_available_end_day,
        toDecimal64OrNull(price_vat_inc, 2) as price_vat_inc,
        toNullable(toInt32(cabin_capacity)) as cabin_capacity,
        toNullable(toInt32(cabin_lid)) as cabin_lid,
        toNullable(toInt32(bucket_authorization_start_day)) as bucket_authorization_start_day,
        toNullable(toInt32(bucket_authorization_end_day)) as bucket_authorization_end_day,
        toNullable(toInt32(forecast_full_day_x)) as forecast_full_day_x,
        toNullable(toInt32(optimization_full_day_x)) as optimization_full_day_x,
        toDecimal64OrNull(unconstrained_demand_bookings, 2) as unconstrained_demand_bookings,
        toDecimal64OrNull(unconstrained_demand_revenue, 2) as unconstrained_demand_revenue,
        toDecimal64OrNull(unconstrained_forecast_bookings, 2) as unconstrained_forecast_bookings,
        toDecimal64OrNull(unconstrained_forecast_revenue, 2) as unconstrained_forecast_revenue,
        toBool(is_optim_current) as is_optim_current,
        toBool(is_last) as is_last,
        now()
    FROM s3(
        '{csv_file_path}',
        '{access_key}',
        '{secret_key}',
        'CSVWithNames',
        'transporter_type String, entity_name String, route_name String, service_id Int64, service_number String,
        service_labels Nullable(String), service_departure_date String, service_origin_station_name String,
        service_destination_station_name String, service_departure_datetime String, service_arrival_datetime String,
        service_timezone String, service_budget_objective Nullable(String), service_yield_objective Nullable(String),
        od_id Int64, od_departure_datetime String, od_arrival_datetime String, od_origin_station_name String,
        od_destination_station_name String, market_name String, market_list_alerts String,
        reference_service_number Nullable(String), reference_service_departure_date Nullable(String),
        event_datetime String, day_x Int64, is_last Int64, service_status String, service_capacity Nullable(Int64),
        service_lid Nullable(Int64), od_status String, market_rank Int64, od_rank Int64,
        service_max_leg_load_factor Nullable(String), service_max_leg_cumulative_sum_net_bookings Nullable(Int64),
        service_optimization_status String, cabin_capacity Nullable(Int64), cabin_lid Nullable(Int64),
        market_cabin_max_leg_load_factor Nullable(String),
        market_cabin_max_leg_cumulative_sum_net_bookings Nullable(Int64),
        od_cabin_forecasted_traffic Nullable(String), od_cabin_forecasted_revenue_vat_inc Nullable(String),
        od_cabin_forecasted_revenue_vat_exc Nullable(String), od_cabin_optimized_traffic Nullable(String),
        od_cabin_optimized_revenue_vat_inc Nullable(String), od_cabin_optimized_revenue_vat_exc Nullable(String),
        od_cabin_last_predicted Nullable(String), od_cabin_last_observed Nullable(String), od_cabin_pointer Int64,
        service_pointer Int64, bucket_name String, bucket_authorization_start_day Nullable(Int64),
        bucket_authorization_end_day Nullable(Int64), cabin_name String, family_name String, bucket_order Int64,
        is_first_available_start_day Int64, is_first_available_end_day Int64, has_pricing_changed_day_x Int64,
        has_pricing_changed_bucket Int64, availability_start_day Nullable(Int64), availability_end_day Nullable(Int64),
        cumul_availability_start_day Int64, cumul_availability_end_day Int64, price_vat_inc Nullable(String),
        cumulative_sum_net_bookings Nullable(Int64), cumulative_sum_net_revenue_vat_inc Nullable(String),
        cumulative_sum_net_revenue_vat_exc String, cumulative_sum_net_ancillary_revenue_vat_inc String,
        cumulative_sum_net_ancillary_revenue_vat_exc String, sum_confirmed_bookings Nullable(Int64),
        sum_net_bookings Nullable(Int64), sum_net_revenue_vat_inc String, sum_net_revenue_vat_exc String,
        sum_net_ancillary_revenue_vat_inc String, sum_net_ancillary_revenue_vat_exc String,
        forecast_full_day_x Nullable(Int64), optimization_full_day_x Nullable(Int64),
        unconstrained_demand_bookings Nullable(String), unconstrained_demand_revenue Nullable(String),
        unconstrained_forecast_bookings Nullable(String), unconstrained_forecast_revenue Nullable(String),
        is_optim_current Int64'
    )
    """


def _passenger_insert_query(csv_file_path: str, *, access_key: str, secret_key: str) -> str:
    return f"""
    INSERT INTO fact_passenger_event (
        time,
        day_x,
        event_datetime,
        transporter_type,
        entity_name,
        route_name,
        service_id,
        service_departure_date,
        service_number,
        service_labels,
        service_status,
        service_origin_station_name,
        service_destination_station_name,
        service_departure_datetime,
        service_arrival_datetime,
        service_timezone,
        market_id,
        market_name,
        market_rank,
        od_id,
        od_status,
        od_origin_station_name,
        od_destination_station_name,
        od_destination_station_id,
        od_departure_datetime,
        od_arrival_datetime,
        od_rank,
        cabin_name,
        family_name,
        bucket_name,
        bucket_order,
        cabin_capacity,
        cabin_lid,
        physical_inventory_name,
        price_vat_inc,
        price_vat_exc,
        base_price_vat_inc,
        bucket_price_vat_inc,
        ancillary_revenue_vat_inc,
        ancillary_revenue_vat_exc,
        event_type,
        booking_key,
        customer_key,
        ticket_category,
        ticket_key,
        fare_code,
        sale_channel_name,
        sale_channel_type,
        is_ticket_exchanged,
        is_confirmed,
        no_show,
        insertion_datetime
    )
    SELECT
        event_datetime as time,
        CAST(day_x AS Int32) as day_x,
        parseDateTime64BestEffort(event_datetime, 3, 'UTC') as event_datetime,
        toLowCardinality(transporter_type) as transporter_type,
        toLowCardinality(entity_name) as entity_name,
        toLowCardinality(route_name) as route_name,
        service_id,
        service_departure_date,
        toString(service_number) as service_number,
        multiIf(
            ifNull(service_labels, '') = '', [],
            splitByString('#~#', ifNull(service_labels, ''))
        ) as service_labels,
        toLowCardinality(service_status) as service_status,
        service_origin_station_name,
        service_destination_station_name,
        parseDateTime64BestEffort(service_departure_datetime, 3, 'UTC') as service_departure_datetime,
        parseDateTime64BestEffort(service_arrival_datetime, 3, 'UTC') as service_arrival_datetime,
        toLowCardinality(service_timezone) as service_timezone,
        market_id,
        toLowCardinality(market_name) as market_name,
        market_rank,
        od_id,
        od_status,
        od_origin_station_name,
        od_destination_station_name,
        od_destination_station_id,
        parseDateTime64BestEffort(od_departure_datetime, 3, 'UTC') as od_departure_datetime,
        parseDateTime64BestEffort(od_arrival_datetime, 3, 'UTC') as od_arrival_datetime,
        od_rank,
        toLowCardinality(toString(cabin_name)) as cabin_name,
        toLowCardinality(family_name) as family_name,
        toLowCardinality(bucket_name) as bucket_name,
        CAST(bucket_order AS Int32) as bucket_order,
        CAST(cabin_capacity AS Nullable(Int32)) as cabin_capacity,
        CAST(cabin_lid AS Nullable(Int32)) as cabin_lid,
        physical_inventory_name,
        toDecimal64OrNull(price_vat_inc, 2) as price_vat_inc,
        toDecimal64OrNull(price_vat_exc, 2) as price_vat_exc,
        toDecimal64(base_price_vat_inc, 2) as base_price_vat_inc,
        toDecimal64OrNull(bucket_price_vat_inc, 2) as bucket_price_vat_inc,
        toDecimal64(ancillary_revenue_vat_inc, 2) as ancillary_revenue_vat_inc,
        toDecimal64(ancillary_revenue_vat_exc, 2) as ancillary_revenue_vat_exc,
        toLowCardinality(event_type) as event_type,
        booking_key,
        customer_key,
        ticket_category,
        ticket_key,
        fare_code,
        sale_channel_name,
        sale_channel_type,
        CAST(is_ticket_exchanged AS Bool) as is_ticket_exchanged,
        CAST(is_confirmed AS Bool) as is_confirmed,
        CAST(no_show AS Bool) as no_show,
        now()
    FROM s3(
        '{csv_file_path}',
        '{access_key}',
        '{secret_key}',
        'CSVWithNames',
        'transporter_type String, entity_name String, route_name String, service_id Int64, service_number String,
        service_labels String, service_departure_date String, service_origin_station_name String,
        service_destination_station_name String, service_departure_datetime String, service_arrival_datetime String,
        service_timezone String, od_id Int64, od_departure_datetime String, od_arrival_datetime String,
        od_origin_station_name String, od_destination_station_id Int64, od_destination_station_name String,
        event_type String, booking_key String, customer_key Nullable(String), ticket_key String, market_id Int64,
        market_name String, market_rank Nullable(Int32), cabin_capacity Nullable(Int64), cabin_lid Nullable(Int64),
        od_rank Nullable(Int32), service_status String, od_status String, physical_inventory_name String,
        cabin_name String, family_name String, bucket_name String, bucket_order Int64,
        bucket_price_vat_inc Nullable(String), is_ticket_exchanged Int64, is_confirmed Int64, day_x Int64,
        price_vat_inc Nullable(String), price_vat_exc Nullable(String), base_price_vat_inc String,
        ancillary_revenue_vat_inc String, ancillary_revenue_vat_exc String, event_datetime String,
        ticket_category Nullable(String), fare_code Nullable(String), sale_channel_name Nullable(String),
        sale_channel_type Nullable(String), no_show Nullable(Int64)'
    )
    """


def _leg_insert_query(csv_file_path: str, *, access_key: str, secret_key: str) -> str:
    return f"""
    INSERT INTO fact_daily_leg_physical_inventory (
        time,
        day_x,
        event_datetime,
        transporter_type,
        entity_name,
        route_name,
        service_number,
        service_labels,
        service_status,
        service_departure_date,
        service_origin_station_name,
        service_destination_station_name,
        service_departure_datetime,
        service_arrival_datetime,
        is_service_peak_leg,
        is_service_max_leg,
        service_max_leg_origin_station_name,
        service_max_leg_destination_station_name,
        leg_id,
        leg_status,
        leg_origin_station_name,
        leg_destination_station_name,
        leg_departure_datetime,
        leg_arrival_datetime,
        leg_order,
        leg_list_alerts,
        cabin_name,
        physical_inventory_name,
        physical_inventory_capacity,
        physical_inventory_lid,
        physical_availability_start_day,
        physical_availability_end_day,
        cumulative_sum_net_revenue_vat_inc,
        cumulative_sum_net_revenue_vat_exc,
        cumulative_sum_net_ancillary_revenue_vat_inc,
        cumulative_sum_net_ancillary_revenue_vat_exc,
        sum_net_revenue_vat_inc,
        sum_net_revenue_vat_exc,
        sum_net_ancillary_revenue_vat_inc,
        sum_net_ancillary_revenue_vat_exc,
        cumulative_sum_net_bookings,
        sum_net_bookings,
        forecast_full_day_x,
        optimization_full_day_x,
        unconstrained_demand_bookings,
        unconstrained_forecast_bookings,
        final_forecast_bookings,
        is_last,
        insertion_datetime,
        service_utc_offset_minutes
    )
    SELECT
        event_datetime as time,
        CAST(day_x AS Int16) as day_x,
        parseDateTime64BestEffort(event_datetime, 3, 'UTC') as event_datetime,
        toLowCardinality(transporter_type) as transporter_type,
        toLowCardinality(entity_name) as entity_name,
        toLowCardinality(route_name) as route_name,
        toString(service_number) as service_number,
        multiIf(
            ifNull(service_labels, '') = '', [],
            splitByString('#~#', ifNull(service_labels, ''))
        ) as service_labels,
        toLowCardinality(service_status) as service_status,
        service_departure_date,
        service_origin_station_name,
        service_destination_station_name,
        parseDateTime64BestEffort(service_departure_datetime, 3, 'UTC') as service_departure_datetime,
        parseDateTime64BestEffort(service_arrival_datetime, 3, 'UTC') as service_arrival_datetime,
        CAST(is_service_peak_leg AS Bool) as is_service_peak_leg,
        CAST(is_service_max_leg AS Bool) as is_service_max_leg,
        service_max_leg_origin_station_name,
        service_max_leg_destination_station_name,
        leg_id,
        leg_status,
        leg_origin_station_name,
        leg_destination_station_name,
        parseDateTime64BestEffort(leg_departure_datetime, 3, 'UTC') as leg_departure_datetime,
        parseDateTime64BestEffort(leg_arrival_datetime, 3, 'UTC') as leg_arrival_datetime,
        CAST(leg_order AS Int32) as leg_order,
        multiIf(
            ifNull(leg_list_alerts, '') = '', [],
            splitByString('#~#', ifNull(leg_list_alerts, ''))
        ) as leg_list_alerts,
        toLowCardinality(toString(cabin_name)) as cabin_name,
        toLowCardinality(physical_inventory_name) as physical_inventory_name,
        CAST(physical_inventory_capacity AS Nullable(Int32)) as physical_inventory_capacity,
        CAST(physical_inventory_lid AS Nullable(Int32)) as physical_inventory_lid,
        CAST(physical_availability_start_day AS Nullable(Int32)) as physical_availability_start_day,
        CAST(physical_availability_end_day AS Nullable(Int32)) as physical_availability_end_day,
        toDecimal64(cumulative_sum_net_revenue_vat_inc, 2) as cumulative_sum_net_revenue_vat_inc,
        toDecimal64(cumulative_sum_net_revenue_vat_exc, 2) as cumulative_sum_net_revenue_vat_exc,
        toDecimal64(cumulative_sum_net_ancillary_revenue_vat_inc, 2) as cumulative_sum_net_ancillary_revenue_vat_inc,
        toDecimal64(cumulative_sum_net_ancillary_revenue_vat_exc, 2) as cumulative_sum_net_ancillary_revenue_vat_exc,
        toDecimal64(sum_net_revenue_vat_inc, 2) as sum_net_revenue_vat_inc,
        toDecimal64(sum_net_revenue_vat_exc, 2) as sum_net_revenue_vat_exc,
        toDecimal64(sum_net_ancillary_revenue_vat_inc, 2) as sum_net_ancillary_revenue_vat_inc,
        toDecimal64(sum_net_ancillary_revenue_vat_exc, 2) as sum_net_ancillary_revenue_vat_exc,
        CAST(cumulative_sum_net_bookings AS Int32) as cumulative_sum_net_bookings,
        CAST(sum_net_bookings AS Int32) as sum_net_bookings,
        CAST(forecast_full_day_x AS Nullable(Int32)) as forecast_full_day_x,
        CAST(optimization_full_day_x AS Nullable(Int32)) as optimization_full_day_x,
        toDecimal64OrNull(unconstrained_demand_bookings, 2) as unconstrained_demand_bookings,
        toDecimal64OrNull(unconstrained_forecast_bookings, 2) as unconstrained_forecast_bookings,
        toDecimal64OrNull(final_forecast_bookings, 2) as final_forecast_bookings,
        CAST(is_last AS Bool) as is_last,
        now(),
        CAST(service_utc_offset_minutes AS Int16) as service_utc_offset_minutes
    FROM s3(
        '{csv_file_path}',
        '{access_key}',
        '{secret_key}',
        'CSVWithNames',
        'event_datetime String, day_x Int64, is_last Int64, service_status String, service_utc_offset_minutes Int64,
        service_max_leg_origin_station_name String, service_max_leg_destination_station_name String,
        transporter_type String, entity_name String,         route_name String, service_number String,
        service_labels Nullable(String), service_departure_date String, service_origin_station_name String,
        service_destination_station_name String, service_departure_datetime String, service_arrival_datetime String,
        leg_id Int64, leg_departure_datetime String, leg_arrival_datetime String, leg_origin_station_name String,
        leg_destination_station_name String, leg_order Int64, leg_list_alerts Nullable(String), leg_status String,
        is_service_max_leg Int64, is_service_peak_leg Int64, cabin_name String, physical_inventory_name String,
        physical_inventory_capacity Nullable(Int64), physical_inventory_lid Nullable(Int64),
        physical_availability_start_day Nullable(Int64),
        physical_availability_end_day Nullable(Int64), cumulative_sum_net_bookings Int64,
        cumulative_sum_net_revenue_vat_inc String, cumulative_sum_net_revenue_vat_exc String,
        cumulative_sum_net_ancillary_revenue_vat_inc String, cumulative_sum_net_ancillary_revenue_vat_exc String,
        sum_net_bookings Int64, sum_net_revenue_vat_inc String, sum_net_revenue_vat_exc String,
        sum_net_ancillary_revenue_vat_inc String, sum_net_ancillary_revenue_vat_exc String,
        forecast_full_day_x Nullable(Int64), optimization_full_day_x Nullable(Int64),
        unconstrained_demand_bookings Nullable(String),
        unconstrained_forecast_bookings Nullable(String), final_forecast_bookings Nullable(String)'
    )
    """
