"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-08-11

Baseline schema of the benchmark tables.

"""
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""\
CREATE TABLE IF NOT EXISTS fact_daily_od_bucket (
    time TIMESTAMP,
    day_x INTEGER,
    event_datetime TIMESTAMP,
    transporter_type VARCHAR,
    entity_name VARCHAR,
    route_name VARCHAR,
    service_id BIGINT,
    service_departure_date DATE,
    service_number VARCHAR,
    service_labels VARCHAR[],
    service_status VARCHAR,
    service_origin_station_name VARCHAR,
    service_destination_station_name VARCHAR,
    service_departure_datetime TIMESTAMP,
    service_arrival_datetime TIMESTAMP,
    service_timezone VARCHAR,
    service_arrival_timezone VARCHAR DEFAULT 'UTC',
    service_budget_objective DECIMAL(10, 2),
    service_yield_objective DECIMAL(10, 2),
    service_capacity INTEGER,
    service_lid INTEGER,
    service_max_leg_load_factor DECIMAL(10, 2),
    service_max_leg_cumulative_sum_net_bookings INTEGER,
    service_optimization_status VARCHAR,
    service_pointer BOOLEAN,
    market_name VARCHAR,
    market_rank INTEGER,
    market_list_alerts VARCHAR[],
    market_cabin_max_leg_load_factor DECIMAL(10, 2),
    market_cabin_max_leg_cumulative_sum_net_bookings INTEGER,
    od_id BIGINT,
    od_status VARCHAR,
    od_origin_station_name VARCHAR,
    od_origin_timezone VARCHAR DEFAULT 'UTC',
    od_destination_station_name VARCHAR,
    od_destination_timezone VARCHAR DEFAULT 'UTC',
    od_departure_datetime TIMESTAMP,
    od_arrival_datetime TIMESTAMP,
    od_rank INTEGER,
    reference_service_number VARCHAR,
    reference_service_departure_date DATE,
    cabin_name VARCHAR,
    od_cabin_forecasted_traffic DECIMAL(10, 2),
    od_cabin_forecasted_revenue_vat_inc DECIMAL(10, 2),
    od_cabin_forecasted_revenue_vat_exc DECIMAL(10, 2),
    od_cabin_optimized_traffic DECIMAL(10, 2),
    od_cabin_optimized_revenue_vat_inc DECIMAL(10, 2),
    od_cabin_optimized_revenue_vat_exc DECIMAL(10, 2),
    od_cabin_last_predicted DECIMAL(10, 2),
    od_cabin_last_observed DECIMAL(10, 2),
    od_cabin_pointer BOOLEAN,
    family_name VARCHAR,
    bucket_name VARCHAR,
    bucket_order INTEGER,
    has_pricing_changed_day_x BOOLEAN,
    has_pricing_changed_bucket BOOLEAN,
    cumulative_sum_net_revenue_vat_inc DECIMAL(10, 2),
    cumulative_sum_net_revenue_vat_exc DECIMAL(10, 2),
    cumulative_sum_net_ancillary_revenue_vat_inc DECIMAL(10, 2),
    cumulative_sum_net_ancillary_revenue_vat_exc DECIMAL(10, 2),
    sum_net_revenue_vat_inc DECIMAL(10, 2),
    sum_net_revenue_vat_exc DECIMAL(10, 2),
    sum_net_ancillary_revenue_vat_inc DECIMAL(10, 2),
    sum_net_ancillary_revenue_vat_exc DECIMAL(10, 2),
    availability_start_day INTEGER,
    availability_end_day INTEGER,
    cumul_availability_start_day INTEGER,
    cumul_availability_end_day INTEGER,
    cumulative_sum_net_bookings INTEGER,
    sum_confirmed_bookings INTEGER,
    sum_net_bookings INTEGER,
    is_first_available_start_day BOOLEAN,
    is_first_available_end_day BOOLEAN,
    price_vat_inc DECIMAL(10, 2),
    cabin_capacity INTEGER,
    cabin_lid INTEGER,
    bucket_authorization_start_day INTEGER,
    bucket_authorization_end_day INTEGER,
    forecast_full_day_x INTEGER,
    optimization_full_day_x INTEGER,
    unconstrained_demand_bookings DECIMAL(10, 2),
    unconstrained_demand_revenue DECIMAL(10, 2),
    unconstrained_forecast_bookings DECIMAL(10, 2),
    unconstrained_forecast_revenue DECIMAL(10, 2),
    is_last BOOLEAN,
    is_optim_current BOOLEAN,
    insertion_datetime TIMESTAMP DEFAULT now(),
    is_service_model_available BOOLEAN
)
""")

    op.execute("""\
CREATE TABLE IF NOT EXISTS fact_daily_leg_physical_inventory (
    time TIMESTAMP,
    day_x SMALLINT,
    event_datetime TIMESTAMP,
    transporter_type VARCHAR,
    entity_name VARCHAR,
    route_name VARCHAR,
    service_number VARCHAR,
    service_timezone VARCHAR DEFAULT 'UTC',
    service_arrival_timezone VARCHAR DEFAULT 'UTC',
    service_labels VARCHAR[],
    service_status VARCHAR,
    service_departure_date DATE,
    service_origin_station_name VARCHAR,
    service_destination_station_name VARCHAR,
    service_departure_datetime TIMESTAMP,
    service_arrival_datetime TIMESTAMP,
    is_service_peak_leg BOOLEAN,
    is_service_max_leg BOOLEAN,
    service_max_leg_origin_station_name VARCHAR,
    service_max_leg_destination_station_name VARCHAR,
    leg_id BIGINT,
    leg_status VARCHAR,
    leg_origin_station_name VARCHAR,
    leg_origin_timezone VARCHAR DEFAULT 'UTC',
    leg_destination_station_name VARCHAR,
    leg_destination_timezone VARCHAR DEFAULT 'UTC',
    leg_departure_datetime TIMESTAMP,
    leg_arrival_datetime TIMESTAMP,
    leg_order INTEGER,
    leg_list_alerts VARCHAR[],
    cabin_name VARCHAR,
    physical_inventory_name VARCHAR,
    physical_inventory_capacity INTEGER,
    physical_inventory_lid INTEGER,
    physical_availability_start_day INTEGER,
    physical_availability_end_day INTEGER,
    cumulative_sum_net_revenue_vat_inc DECIMAL(10, 2),
    cumulative_sum_net_revenue_vat_exc DECIMAL(10, 2),
    cumulative_sum_net_ancillary_revenue_vat_inc DECIMAL(10, 2),
    cumulative_sum_net_ancillary_revenue_vat_exc DECIMAL(10, 2),
    sum_net_revenue_vat_inc DECIMAL(10, 2),
    sum_net_revenue_vat_exc DECIMAL(10, 2),
    sum_net_ancillary_revenue_vat_inc DECIMAL(10, 2),
    sum_net_ancillary_revenue_vat_exc DECIMAL(10, 2),
    cumulative_sum_net_bookings INTEGER,
    sum_net_bookings INTEGER,
    forecast_full_day_x INTEGER,
    optimization_full_day_x INTEGER,
    unconstrained_demand_bookings DECIMAL(10, 2),
    unconstrained_forecast_bookings DECIMAL(10, 2),
    is_last BOOLEAN,
    final_forecast_bookings DECIMAL(10, 2),
    insertion_datetime TIMESTAMP DEFAULT now(),
    service_utc_offset_minutes SMALLINT DEFAULT 0
)
""")

    op.execute("""\
CREATE TABLE IF NOT EXISTS fact_passenger_event (
    time TIMESTAMP,
    day_x INTEGER,
    event_datetime TIMESTAMP,
    transporter_type VARCHAR,
    entity_name VARCHAR,
    route_name VARCHAR,
    service_id BIGINT,
    service_departure_date DATE,
    service_number VARCHAR,
    service_labels VARCHAR[],
    service_status VARCHAR,
    service_origin_station_name VARCHAR,
    service_destination_station_name VARCHAR,
    service_departure_datetime TIMESTAMP,
    service_arrival_datetime TIMESTAMP,
    service_timezone VARCHAR,
    service_arrival_timezone VARCHAR DEFAULT 'UTC',
    market_id BIGINT,
    market_name VARCHAR,
    market_rank INTEGER,
    od_id BIGINT,
    od_status VARCHAR,
    od_origin_station_name VARCHAR,
    od_origin_timezone VARCHAR DEFAULT 'UTC',
    od_destination_station_name VARCHAR,
    od_destination_timezone VARCHAR DEFAULT 'UTC',
    od_destination_station_id BIGINT,
    od_departure_datetime TIMESTAMP,
    od_arrival_datetime TIMESTAMP,
    od_rank INTEGER,
    cabin_name VARCHAR,
    family_name VARCHAR,
    bucket_name VARCHAR,
    bucket_order INTEGER,
    cabin_capacity INTEGER,
    cabin_lid INTEGER,
    physical_inventory_name VARCHAR,
    price_vat_inc DECIMAL(10, 2),
    price_vat_exc DECIMAL(10, 2),
    base_price_vat_inc DECIMAL(10, 2),
    bucket_price_vat_inc DECIMAL(10, 2),
    ancillary_revenue_vat_inc DECIMAL(10, 2),
    ancillary_revenue_vat_exc DECIMAL(10, 2),
    event_type VARCHAR,
    booking_key VARCHAR,
    customer_key VARCHAR,
    ticket_category VARCHAR,
    ticket_key VARCHAR,
    fare_code VARCHAR,
    sale_channel_name VARCHAR,
    sale_channel_type VARCHAR,
    is_ticket_exchanged BOOLEAN,
    is_confirmed BOOLEAN,
    no_show BOOLEAN,
    insertion_datetime TIMESTAMP DEFAULT now()
)
""")


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS fact_passenger_event")
    op.execute("DROP TABLE IF EXISTS fact_daily_leg_physical_inventory")
    op.execute("DROP TABLE IF EXISTS fact_daily_od_bucket")
